# Generated by ChatGPT for Django 5.2
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defect",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("defect_id", models.CharField(help_text="Human-friendly identifier (e.g., DF-1001).", max_length=32, unique=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("detected_on", models.DateField(db_index=True)),
                ("product", models.CharField(blank=True, db_index=True, max_length=120)),
                ("component", models.CharField(blank=True, db_index=True, max_length=120)),
                ("environment", models.CharField(blank=True, db_index=True, max_length=120)),
                ("severity", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], db_index=True, default="MEDIUM", max_length=16)),
                ("priority", models.CharField(choices=[("P4", "P4"), ("P3", "P3"), ("P2", "P2"), ("P1", "P1")], db_index=True, default="P3", max_length=2)),
                ("status", models.CharField(choices=[("NEW", "New"), ("TRIAGED", "Triaged"), ("IN_PROGRESS", "In progress"), ("RCA", "RCA"), ("ACTIONS", "Actions"), ("VERIFIED", "Verified"), ("CLOSED", "Closed"), ("REJECTED", "Rejected")], db_index=True, default="NEW", max_length=24)),
                ("reported_by", models.CharField(blank=True, db_index=True, max_length=120)),
                ("owner", models.CharField(blank=True, db_index=True, max_length=120)),
                ("assignee", models.CharField(blank=True, db_index=True, max_length=120)),
                ("tags", models.CharField(blank=True, help_text="Comma-separated tags for simple filtering.", max_length=300)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("enabled", models.BooleanField(db_index=True, default=True)),
                ("event_type", models.CharField(choices=[("DEFECT_OVERDUE", "Defect overdue"), ("ACTION_OVERDUE", "Action overdue"), ("STATUS_CHANGED", "Status changed"), ("HIGH_SEVERITY", "High severity")], db_index=True, max_length=32)),
                ("channel", models.CharField(choices=[("IN_APP", "In-app"), ("EMAIL", "Email")], default="IN_APP", max_length=16)),
                ("min_severity", models.CharField(blank=True, choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], db_index=True, max_length=16, null=True)),
                ("parameters", models.TextField(blank=True, help_text="Optional parameters in JSON format (stored as text for portability).")),
            ],
        ),
        migrations.CreateModel(
            name="RCAAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("COMPLETE", "Complete")], db_index=True, default="DRAFT", max_length=16)),
                ("root_cause", models.TextField(blank=True)),
                ("contributing_factors", models.TextField(blank=True)),
                ("completed_by", models.CharField(blank=True, db_index=True, max_length=120)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("defect", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="rca", to="api.defect")),
            ],
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("action_type", models.CharField(choices=[("CORRECTIVE", "Corrective"), ("PREVENTIVE", "Preventive")], db_index=True, default="CORRECTIVE", max_length=16)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("IN_PROGRESS", "In progress"), ("DONE", "Done"), ("CANCELED", "Canceled"), ("OVERDUE", "Overdue")], db_index=True, default="OPEN", max_length=16)),
                ("owner", models.CharField(blank=True, db_index=True, max_length=120)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("defect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corrective_actions", to="api.defect")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("from_status", models.CharField(choices=[("NEW", "New"), ("TRIAGED", "Triaged"), ("IN_PROGRESS", "In progress"), ("RCA", "RCA"), ("ACTIONS", "Actions"), ("VERIFIED", "Verified"), ("CLOSED", "Closed"), ("REJECTED", "Rejected")], max_length=24)),
                ("to_status", models.CharField(choices=[("NEW", "New"), ("TRIAGED", "Triaged"), ("IN_PROGRESS", "In progress"), ("RCA", "RCA"), ("ACTIONS", "Actions"), ("VERIFIED", "Verified"), ("CLOSED", "Closed"), ("REJECTED", "Rejected")], max_length=24)),
                ("changed_by", models.CharField(blank=True, db_index=True, max_length=120)),
                ("comment", models.TextField(blank=True)),
                ("defect", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workflow_history", to="api.defect")),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiveWhyEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("why_number", models.PositiveSmallIntegerField(help_text="1..5", validators=[django.core.validators.MinValueValidator(1)])),
                ("problem_statement", models.CharField(blank=True, max_length=300)),
                ("why_text", models.TextField()),
                ("rca", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="five_whys", to="api.rcaanalysis")),
            ],
            options={
                "ordering": ["why_number"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("level", models.CharField(choices=[("INFO", "Info"), ("WARNING", "Warning"), ("CRITICAL", "Critical")], db_index=True, default="INFO", max_length=16)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("acknowledged", models.BooleanField(db_index=True, default=False)),
                ("acknowledged_by", models.CharField(blank=True, db_index=True, max_length=120)),
                ("acknowledged_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("corrective_action", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_events", to="api.correctiveaction")),
                ("defect", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="alert_events", to="api.defect")),
                ("rule", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="events", to="api.notificationrule")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="defect",
            index=models.Index(fields=["status", "severity"], name="api_defect_status_8a2167_idx"),
        ),
        migrations.AddIndex(
            model_name="defect",
            index=models.Index(fields=["status", "priority"], name="api_defect_status_4ed28b_idx"),
        ),
        migrations.AddIndex(
            model_name="defect",
            index=models.Index(fields=["product", "component"], name="api_defect_product_4f5b43_idx"),
        ),
        migrations.AddIndex(
            model_name="defect",
            index=models.Index(fields=["owner", "assignee"], name="api_defect_owner_53c323_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(fields=["enabled", "event_type"], name="api_notifi_enabled_2fdbf0_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(fields=["channel", "enabled"], name="api_notifi_channel_9c5c58_idx"),
        ),
        migrations.AddIndex(
            model_name="rcaanalysis",
            index=models.Index(fields=["status", "completed_at"], name="api_rcaan_status_545193_idx"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["defect", "status"], name="api_corre_defect_8e9b4d_idx"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["status", "due_date"], name="api_corre_status_4f9901_idx"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["owner", "status"], name="api_corre_owner_8441d2_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowhistory",
            index=models.Index(fields=["defect", "created_at"], name="api_workf_defect_c4e5b2_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowhistory",
            index=models.Index(fields=["to_status", "created_at"], name="api_workf_to_sta_4f252f_idx"),
        ),
        migrations.AddIndex(
            model_name="fivewhyentry",
            index=models.Index(fields=["rca", "why_number"], name="api_fivew_rca_8b4c75_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["acknowledged", "level"], name="api_alert_ackno_6b5b43_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["defect", "created_at"], name="api_alert_defect_1a9b8e_idx"),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(fields=["corrective_action", "created_at"], name="api_alert_corre_0a4d24_idx"),
        ),
        migrations.AddConstraint(
            model_name="workflowhistory",
            constraint=models.CheckConstraint(check=~models.Q(("from_status", models.F("to_status"))), name="workflow_from_status_not_equal_to_status"),
        ),
        migrations.AddConstraint(
            model_name="fivewhyentry",
            constraint=models.CheckConstraint(check=models.Q(("why_number__gte", 1), ("why_number__lte", 5)), name="fivewhy_why_number_between_1_and_5"),
        ),
        migrations.AddConstraint(
            model_name="fivewhyentry",
            constraint=models.UniqueConstraint(fields=("rca", "why_number"), name="fivewhy_unique_number_per_rca"),
        ),
        migrations.AddConstraint(
            model_name="alertevent",
            constraint=models.CheckConstraint(check=(models.Q(("defect__isnull", False)) | models.Q(("corrective_action__isnull", False))), name="alertevent_requires_defect_or_action"),
        ),
    ]
